export const barChartData = {};

export const tableData = [
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
  { no: 1, customer: "Celica", location: "New York", favouriteProduct:"Adidas",orders:30,totalSpending:2456 },
];
